services:
  db:
    image: postgres:16
    container_name: issueflow_db
    environment:
      POSTGRES_USER: issueflow
      POSTGRES_PASSWORD: issueflow
      POSTGRES_DB: issueflow
    ports:
      - "5433:5432"
    volumes:
      - issueflow_pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: issueflow_api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - ./secrets:/app/secrets:ro
    depends_on:
      - db

volumes:
  issueflow_pgdata:
